name: zineb_el_chat
version: 1.0.0+1
publish_to: none
description: A Flutter chat app project by Zineb El.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  flutter_icons: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  get: 4.1.4
  get_storage: ^2.0.2
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.4.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/images/